### ISSUE TITLE
Select trees for first batch of dendrometers (n=8)

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/AutoDendrometers#1]
# Considerations
## Species
- We want to represent species in part based on their [contribution to ANPP](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/summary_data/ANPP_total_and_by_species.csv)
- It's also interesting to consider species that differ ecologically: ring- vs diffuse-porous, shade-intolerant vs shade-tolerant, etc.

## Size classes
- I'd like to consider trees that differ in height/ crown position

## Replicates
- Growth can be variable around the circumference of a tree, so an ideal strategy would have some replicates
- Obviously, it will be important to bring in replication, but for the initial small batch, the goal is to understand how the dendrometers work and get some preliminary data on differences across species/ sizes.

## Specific trees
- All auto dendrometers should go on trees with biweekly dendrometer band measurements, ideally with a very good long-term record.
- If possible, it would be good to get trees that have been cored.
- All else being equal, it would be good to place dendrometers on trees that have been included in other studies (e.g., t-lidar)

**Comment by teixeirak** [comment]
# Initial idea
## Diversity of species x sizes (n=6 of 8 bands)
### Species
-  *Liriodendron tulipifera* (1st in ANPP, diffuse-porous, shade-intolerant)
-  *Quercus alba* (2nd in ANPP, ring-porous)
- *Fagus grandifolia* (12th in ANPP, diffuse-porous, shade-tolerant) - interesting for its very different ecological strategy
### Size classes
- canopy dominants  
- understory

## Within-tree variation (n=2 of 8 bands)
- use the additional 2 bands as replicates on 1 or 2 of the trees above (i.e., one tree gets 3 dendrometers, or 2 get 2 each)

**Comment by teixeirak** [comment]
@rudeboybert , what do you think of this strategy?

**Comment by teixeirak** [comment]
I've added [this file](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/candidate_trees.csv), which I manually compiled referencing from dendro_trees, Mortality_Survey_2021, scbi.dendroAll_2021, and dbh_growth_dendrobands.pdf.  It's a start, but I need to think more about priorities in terms of size classes, importance of a great dendro band record, how valuable it is to have a tree-ring record for the tree, etc.

@rudeboybert , I'd be interested to hear your take, from the perspective of your work, as to what would be valuable to prioritize.

**Comment by teixeirak** [comment]
# Alternative Option
## 4 species x 2 individuals 
### Species
-  *Liriodendron tulipifera* (1st in ANPP, diffuse-porous, shade-intolerant)
-  *Quercus rubra* (2nd in ANPP, ring-porous)
- *Fagus grandifolia* (8th in ANPP, diffuse-porous, shade-tolerant) - interesting for its very different ecological strategy
-  *Quercus alba*? (3rd in ANPP, ring-porous)
- *Carya glabra*? (5th in ANPP - most productive Carya, ring-porous) - interesting in that it represents another genus and  can have very pronounced winter shrinkage (see below). Disadvantage is that we only have biannual bands for 3, none with cores, and all small (<30cm). 
<img width="831" alt="image" src="https://user-images.githubusercontent.com/6355854/156175472-67b1f145-fc81-4dc3-8223-80461f261773.png">

**Comment by rudeboybert** [comment]
Some things that immediately come to mind:

- In the [data fusion model](https://github.com/SCBI-ForestGEO/bayesian_data_fusion/) we currently have t, t+1, t+2 increments in months. We do this b/c we want to use the cores data which go really far back. Thus using time scales more refined than month lead to computational run-time and storage memory issues.
- Thus for many biweekly measurements I use a clumsy approach to determine a given month's measure: I only use the first measurement for that month i.e. I throw out all other measurements for that month. From my understanding of how AD work, we'd only be throwing away a lot more data.
- My gut feeling is that rather than worry right now about how we can fit AD measurements into some omnibus model for growth that uses all data sources, we view this as a trial run. One where we can ascertain what is/isn't captured by AD vs biweekly bands and have a clear take home message of the benefits. Kind of like the clear take home benefit of biweekly band measurements over biannual dendroband/annual dbh tape measurements: we can model *within* year variation in growth as a function of *within* year variation in climate
- Perhaps our focus should be within day variations? For example, I read with climate change that the increase in temperature is not uniform: [night time temperatures are increasing faster than daytime temperatures](https://www.popsci.com/story/environment/warming-nighttime-temperatures-climate/). 
- Such modeling would also be much more in line with one of the tenets of kind of forecasting in ecological forecasting: the forecasting has to be rapid, near-term, and iterative. Even if the forecasts aren't as sophisticated as the data fusion model above.

**Comment by rudeboybert** [comment]
As for what stems we should focus on then: stems that we expect the greatest within day variation in size?

**Comment by teixeirak** [comment]
I agree that the auto dendrometers are complete overkill for your data fusion model, although they would be helpful for capturing winter patterns, which we haven't been getting with the manual bands. 

We previously talked about maybe creating a seasonal forecast someday, but that's obviously more of a dream at this point.

I'm not sure we'd want to get into within-day variations, although those are fascinating-- linked to tree hydraulics, sap flux, etc.

**Comment by rudeboybert** [comment]
sounds good. could you articulate what your vision of the goal of this pilot study is? I have it stuck in mind that this is all strictly about comparing the variation in size captured by AD vs the variation in size captured by biweekly bands

**Comment by teixeirak** [comment]
Here's my current plan (current selection in [this doc](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/candidate_trees.csv)): 

# 4 species x 2 individuals 
## Species
Species include the two most dominant (by ANPP) species in diffuse-porous and ring-porous groups:

-  *Liriodendron tulipifera* (1st in ANPP, diffuse-porous, shade-intolerant)
-  *Quercus rubra* (2nd in ANPP, ring-porous)
-  *Quercus alba* (3rd in ANPP, ring-porous)
- *Fagus grandifolia* (8th in ANPP, diffuse-porous, shade-tolerant) - interesting for its very different ecological strategy

## Sizes
Each species has a representative in each of two size classes:
- huge (≥95 cm DBH, crown.illum = 3 or 4)
- large (35 - 70, crown.illum <4)

## Additional criteria
- good long-term biweekly record (required)
- existing tree-ring record (preferred)
- Tree is growing vigorously : >7 mm circumference growth in 2021
- Tree is healthy. Most have "A" status in 2021 census, but "AU" allowed if damage is minor and tree is growing vigorously.

**Comment by teixeirak** [comment]
> sounds good. could you articulate what your vision of the goal of this pilot study is? I have it stuck in mind that this is all strictly about comparing the variation in size captured by AD vs the variation in size captured by biweekly bands

Good question!

# Goals:
- Test the functioning of these dendrometers. Note that other researchers have already tried and given me very positive reports, so the main question is whether we like working with them. (*For this goal, it doesn't matter which trees we select.*)
- Gain a better understanding of seasonal growth patterns, particularly at the edges of the growing season and over winter, when we haven't monitored. This can help fill in gaps in our understanding of seasonal patterns at the site and can inform our decisions about when we make manual measurements. This is likely to contribute to your data fusion.
- Start to understand differential responses of growth to climatic conditions across species/ size classes/ levels of crown exposure (although I'm currently selecting just dominant/ codominant trees)
- Assuming we like these, start a long-term record that will be used to understand the climate sensitivity of growth on time scales <1yr and how this varies across species/ size classes.

**Comment by teixeirak** [comment]
Another option: 

# 4 species x 2 canopy positions  - OPTION B
## Species
Species include most productive species in each of the genera that contribute most to productivity: 2 diffuse-porous and 2 ring-porous:

-  *Liriodendron tulipifera* (1st in ANPP, diffuse-porous, shade-intolerant)
-  *Quercus rubra* (2nd in ANPP, ring-porous)
- *Fagus grandifolia* (8th in ANPP, diffuse-porous, shade-tolerant) - interesting for its very different ecological strategy
- *Carya glabra* (5th in ANPP - most productive Carya, ring-porous) - interesting in that it represents another genus and  can have very pronounced winter shrinkage and water responses. Disadvantage is that we only have biannual bands for 3, none with cores, and all small (<30cm). 

## Sizes
Each species has a representative in each of the following crown positions:
- canopy dominant (≥60 cm DBH, crown.illum = 3 or 4)
- understory (<30 cm DBH, crown.illum = 1 or 2 )

## Additional criteria
- good long-term dendroband record (biweekly strongly preferred)
- existing tree-ring record (preferred)
- Tree is growing: >2 mm circumference growth in 2021
- Tree is healthy. Most have "A" status in 2021 census, but "AU" allowed if damage is minor and tree is growing vigorously.

**Comment by teixeirak** [comment]
We went with option B!
