### ISSUE TITLE
find and buy extra mounting screws

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/AutoDendrometers#10]
I requested extra screws from Tomst. Their response:

It will be a lot cheaper for you to buy them on your own.
The shipping costs alone would far outweigh the cost of the screws.
These are its parameters:
              A2 Stainless steel (also referred to as 304 or 18/8)
              Length: 100mm
              Diameter: 6mm
 
I unfortunately do not know of specific stores in the US that would have it, but they should hopefully have them at hardware stores.
Let me know if you have trouble sourcing them. In that case, we would of course ship a few extras to you.

**Comment by teixeirak** [comment]
I suspect Amazon would have these, if not available at a Hardware store. 

@jenajordan , if you have a chance to see if you can find some, that would be helpful. Or I'll get to this later.

Note: I'm not sure exactly how to refer to them/ whether "screws" is the best term.

**Comment by teixeirak** [comment]
Ace Hardware Fairfax does not carry these.

**Comment by teixeirak** [comment]
This is called a **hanger bolt**.

**Comment by teixeirak** [comment]
I cannot find these on [Amazon](https://smile.amazon.com/s?k=Bolts&rh=n%3A16310091%2Cn%3A383599011%2Cn%3A17290024011%2Cn%3A17416539011%2Cp_n_material_browse%3A17548971011&content-id=amzn1.sym.918a99dd-4826-4c0a-be33-a6705d69c4cf:amzn1.sym.918a99dd-4826-4c0a-be33-a6705d69c4cf&crid=1OTL1KIUNR4EU&pd_rd_r=78adde1f-8484-44ec-9bfc-2cd92ae49691&pd_rd_w=D80KA&pd_rd_wg=0nbv5&pf_rd_p=918a99dd-4826-4c0a-be33-a6705d69c4cf&pf_rd_r=XHWHT8PBP9RQT5A0VH7X&pid=Wo48gmy&sprefix=hanger+bolt+a2+stainless+steel,aps,69&ref=sr_es_fst_blt&page=1).

I've requested that Tomst send some extras in upcoming shipments.

**Comment by jenajordan** [comment]
@teixeirak how many hanger bolts do we need? I will see if I can find some at the local hardware store.

**Comment by teixeirak** [comment]
If you can find them, it would be good to get a decent supply— about 10? I assume they’ll be cheap and that the hard part is finding them. Another option may be a hardware store online. But we’re ordering new dendrometers now, so it shouldn’t be a long wait.

**Comment by teixeirak** [comment]
@jenajordan , I have placed an order for more dendrometers, and they will send extra bolts. So no need to pursue this further (although it could be useful to find a source).

**Comment by jenajordan** [comment]
Okay will do, thanks for letting me know.  There is a hardware store a few blocks from my house - I will at least check and see if they have some.
