### ISSUE TITLE
make map of trees with dendrometers

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/AutoDendrometers#14]
@ValentineHerr , could you please make a map of the [dendrometer trees](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/data/PointDendrometerTrees.csv)? If you're able to do it today, it would be helpful to have for tomorrow. (Sorry for the last minute request! We'll be fine if you don't have time.)

**Comment by ValentineHerr** [comment]
Sorry I did not see this until now...

Valentine Herrmann
________________________________
Research Assistant
Smithsonian Institution
Smithsonian Conservation Biology Institute
1500 Remount Rd.; Front Royal, VA 22630 USA
1-540-635-6549 | ***@***.***
________________________________
From: Kristina Anderson-Teixeira ***@***.***>
Sent: Wednesday, February 22, 2023 14:49
To: SCBI-ForestGEO/AutoDendrometers ***@***.***>
Cc: Herrmann, Valentine ***@***.***>; Mention ***@***.***>
Subject: [SCBI-ForestGEO/AutoDendrometers] make map of trees with dendrometers (Issue #14)


External Email - Exercise Caution

@ValentineHerr<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FValentineHerr&data=05%7C01%7Cherrmannv%40si.edu%7Cdeaa719322744fb4e3ad08db150df66f%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638126921942528791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DiWYZTyIBfKteflLxuohxKbPh5OHf2rgNlo0czIjgro%3D&reserved=0> , could you please make a map of the dendrometer trees<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FAutoDendrometers%2Fblob%2Fmain%2Fdata%2FPointDendrometerTrees.csv&data=05%7C01%7Cherrmannv%40si.edu%7Cdeaa719322744fb4e3ad08db150df66f%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638126921942528791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rhul%2FiiqsOgMap3rHgojx6XAw%2FjHo0Yfmz0LkEiTbT0%3D&reserved=0>? If you're able to do it today, it would be helpful to have for tomorrow. (Sorry for the last minute request! We'll be fine if you don't have time.)
