### ISSUE TITLE
add downloaded data to GitHub

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/AutoDendrometers#5]
Hi @teixeirak, 
  I've exported the data from the Microsoft Surface. Would you like me to add all of the files to the 'data' folder here? I see there are files 'binary', 'data', and 'command' files and some .bmp graphs and didn't want to dump everything at once if you would prefer some other kind of organization.

**Comment by jess-shue** [comment]
@teixeirak  Just attempted to upload files, and 'uploads are disabled, file uploads require push access to the repository'. Should I be added somehow?

**Comment by teixeirak** [comment]
Sorry about that! You should be able to push now. I also added you as a member of the organization, which should allow you to edit/push to any repo.

**Comment by jess-shue** [comment]
No problem, thank you! Files were just added.
