### ISSUE TITLE
Select trees for second batch of dendrometers (n=16) 

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/AutoDendrometers#7]
# Goal
- understand climate sensitivity of stem growth and woody ANPP_woody
- therefore, need to represent species that contribute most to ANPP_woody
- also want to understand how this varies with tree size/ across forest strata

# Considerations

## Species
- We want to represent species in part based on their [contribution to ANPP](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/summary_data/ANPP_total_and_by_species.csv)
- It's also interesting to consider species that differ ecologically: ring- vs diffuse-porous, shade-intolerant vs shade-tolerant, etc.

## Size classes
- I'd like to consider trees that differ in height/ crown position

## Replicates
- Growth can be variable around the circumference of a tree, so an ideal strategy would have some replicates
- Obviously, it will be important to bring in replication, but for this second small batch, my priority is to get a bring in a broader representation of species/ sizes.

## Specific trees
- All auto dendrometers should go on trees with biweekly dendrometer band measurements, ideally with a very good long-term record.
- If possible, it would be good to get trees that have been cored.
- All else being equal, it would be good to place dendrometers on trees that have been included in other studies (e.g., t-lidar)

**Comment by teixeirak** [comment]
#  What we have so far (n=8)

# 4 species x 2 canopy positions  
## Species
Species include most productive species in each of the genera that contribute most to productivity: 2 diffuse-porous and 2 ring-porous:

-  *Liriodendron tulipifera* (1st in ANPP, diffuse-porous, shade-intolerant)
-  *Quercus rubra* (2nd in ANPP, ring-porous)
- *Fagus grandifolia* (8th in ANPP, diffuse-porous, shade-tolerant) - interesting for its very different ecological strategy
- *Carya glabra* (5th in ANPP - most productive Carya, ring-porous) - interesting in that it represents another genus and  can have very pronounced winter shrinkage and water responses. Disadvantage is that we only have biannual bands for 3, none with cores, and all small (<30cm). 

## Sizes
Each species has a representative in each of the following crown positions:
- canopy dominant (≥60 cm DBH, crown.illum = 3 or 4)
- understory (<30 cm DBH, crown.illum = 1 or 2 )

## Additional criteria
- good long-term dendroband record (biweekly strongly preferred)
- existing tree-ring record (preferred)
- Tree is growing: >2 mm circumference growth in 2021
- Tree is healthy. Most have "A" status in 2021 census, but "AU" allowed if damage is minor and tree is growing vigorously.

**Comment by teixeirak** [comment]
The latest set of dendro bands is here: https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_intraannual_2022-06.csv

**Comment by teixeirak** [comment]
Here's my initial selection, with selected species highlighted. 
Green = dominant canopy species, excluding FRAM. This includes all tree-ring chronologies (excluding FRAM and FRNI).
Yellow = 3 understory species (selected in part because they have dendro bands)

![image](https://user-images.githubusercontent.com/6355854/173701998-a7d19d42-f468-4a30-9eba-13cf3af80b53.png)

**Comment by teixeirak** [comment]
I messed up on that last round-- planned for 24 new trees rather than 16 (24 will be total n dendrometers). Here's an updated species plan:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/6355854/175121051-1e582db1-f198-4912-be45-65f822290142.png">

This gets 2 individuals of each species with a tree-ring chronology, minus *Fraxinus*.

**Comment by teixeirak** [comment]
14 are allocated; I still need to find two more.

**Comment by teixeirak** [comment]
@jenajordan , here's how to select trees:

- [2022_06_candidate_trees_2.csv](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/2022_06_candidate_trees_2.csv) has the list of trees for potential install. This is the one I was using yesterday, but with the trees and species for which bands have already been installed. Columns `tag` through `dendro.start.date` are all copied from [dendro_trees.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/data/dendro_trees.csv). The other fields I've filled in from other data sheets.
- I think the easiest ways to find trees is to start with [scbi.dendroAll_2022.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/data/scbi.dendroAll_2022.csv) or [scbi.dendroAll_2021.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/data/scbi.dendroAll_2021.csv). I filter by species and look at `dbh` field to get an idea of size. I give precedence to trees being measured biweekly. I then look at [mortality_2021.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/mortality_2021.csv) to retrieve latest status (AU okay if growing well and looks healthy in the field), crown illumination index (1 or 2 for understory, 3 or 4 for canopy), and  2018 dbh. 
- We need to find 2 trees: JUNI- understory and QUVE-understory. 
  - QUVE: I believe I already checked the smaller QUVE individuals with dendro bands, and the one I looked at in the field yesterday (201432) seemed like the best option but was definitely not understory. I had eliminated tree 80121 because it was unhealthy, but you might check it's recent growth (okay if >2 mm circumference growth/yr) and look at in the field. You might double check that I didn't miss any good candidates with dendro bands. It may be that we need to add a dendro band to an understory QUVE, in which case you can pick candidates based on [mortality_2021.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/mortality_2021.csv).
  - JUNI:  I only considered the individuals with biweekly bands, so hopefully you can find some good choices among the biannual bands and switch one over to biweekly readings.

**Comment by teixeirak** [comment]
[2022_06_candidate_trees_2.csv](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/2022_06_candidate_trees_2.csv) is not very well organized and has no metadata, as it's just my planning document that I never expected to share with others. So let me know what doesn't make sense.

**Comment by jenajordan** [comment]
@teixeirak okay. At first glance, ones noted 'approved' means a go for me? Where are the ones we already mounted - I don't see them listed - unless I'm missing something

**Comment by teixeirak** [comment]
Yes, the ones listed as approved are ones that I visited in the field and decided are good.

The file I used yesterday is [2022_06_candidate_trees.csv](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/2022_06_candidate_trees.csv). New file [2022_06_candidate_trees_2.csv](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/doc/planning/2022_06_candidate_trees_2.csv) is updated to include only the ones relevant to you. The ones installed yesterday are already listed in [PointDendrometerTrees.csv](https://github.com/SCBI-ForestGEO/AutoDendrometers/blob/main/data/PointDendrometerTrees.csv).

**Comment by teixeirak** [comment]
It will be easier to open it in Excel or R Studio (from the cloned repository).

**Comment by teixeirak** [comment]
For 121374 (JUNI), I had a note that it was not growing according to the 2022 dendro data, in which case I'd want to avoid it. Could you please check on that? And do you think it's our best option for an understory JUNI with a dendro band? The other option would be to add a dendro band to a tree that currently doesn't have one.

For 201432, I believe we (or I) checked it in the field and that it was a solid 3 or maybe even 4. Is that our best option for an understory QUVE with a dendro band? Again, the other option would be to add a dendro band to a tree that currently doesn't have one.

**Comment by teixeirak** [comment]
moved to issue #13
